### ISSUE TITLE
Is there a way to show the output audio wave?

### ISSUE THREAD

**Issue by mohpor** [stefanceriu/SCSiriWaveformView#8]
Hi, this is more than gorgeous, really, and I want to use it to display the waveform of my output source (I'm streaming some audio), is there a way to:
1- Assign input source as system output source (I'm just guessing)?
2- If so, I guess we will need to request for permission, is there a workaround for that? it seems kind of annoying to ask permission from user for an activity which we don't want to do.

Thanks for the library and for the probable time your gonna spend investigating this.

**Comment by nverinaud** [comment]
Hi @mohpor,

If I understand your question correctly, you want to display a waveform and have it react when the audio you are outputting changes in intensity ?

You should look at the [_Using Audio Level Metering_](https://developer.apple.com/library/ios/documentation/AVFoundation/Reference/AVAudioPlayerClassReference/index.html#//apple_ref/doc/uid/TP40008067-CH1-SW20) section of [AVAudioPlayer](https://developer.apple.com/library/ios/documentation/AVFoundation/Reference/AVAudioPlayerClassReference/index.html). 

It allows you to retrieve the same value used in the demo of this lib but for audio output instead of audio input.

With these values, you just need to call `-[SCSiriWaveformView updateWithLevel:]`.

**Comment by mohpor** [comment]
Thanks @nverinaud , you're right, I want to show my output spectrum using this gorgeous waveform.
I've investigated some in `AVAudioPlayer` but unfortunately I can't get it to work with HTTP Live Streaming (m3u8). It just won't play. 
I get how this library works but I can't get that audio level!
It might be a good addition to the demo app too. If you have some time I wish you could investigate it, I'm gonna do it anyway but your knowledge of AV is far more superior than mine.
I'll let you know if I could come up with a solution.
Thanks

**Comment by stefanceriu** [comment]
That's a really good idea.. so I've added a simple playback example to the demo project :)
You might also want to check out Apple's AVTouch sample project for more info: https://developer.apple.com/library/ios/samplecode/avTouch

Thanks !
